site_name: Unified Interpretation (UI) Review Portal
site_description: Guide to the IACS UI Review Portal - access, and the Power Apps review application.

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/cog-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/cog-outline
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.footer
  

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - toc:
      permalink: true
      toc_depth: 2-4

nav:
  - Home: index.md

copyright: Copyright &copy; 2026 International Association of Classification Societies (IACS). All rights reserved.
